[package]
name = "ytbgen"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
codegen = { git = "https://github.com/carllerche/codegen.git", version = "0.1.3" }
pest = "2.7.14"
pest_derive = "2.7.14"
